### ISSUE TITLE
Signal External Links

### ISSUE THREAD

**Issue by HalosGhost** [HalosGhost/halosgho.st#13]
For accessibility, and general usability, we should add some kind of signal to suggest that a link will leave our site (à la Wikipedia's external-link icon).

We could do this entirely in CSS and text by doing something like this:

```css
a[href^="http"]:after,
a[href^="https"]:after{
    content:"(External Link)";
    margin-left:0.3rem;
}
```
